from rest_framework import viewsets, filters, views, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny
from django_filters.rest_framework import DjangoFilterBackend
from django.core.mail import EmailMessage
from django.core.files.base import ContentFile
from django.conf import settings
from django.db.models import Sum, Count, Q
from django.utils import timezone
from datetime import timedelta
from core.models import (
    Client, LivestockType, Invoice, Payment, Ticket, SubscriptionModule,
    Reminder, GeneticsSerial, ActivityLog, ClientFile, IssueCategory, Contact,
    Todo, Project,
)
from core.serializers import (
    ClientSerializer, ClientDetailSerializer, LivestockTypeSerializer,
    InvoiceSerializer, PaymentSerializer, TicketSerializer, SubscriptionModuleSerializer,
    ReminderSerializer, GeneticsSerialSerializer, ClientFileSerializer, IssueCategorySerializer,
    ContactSerializer, ActivityLogSerializer, TodoSerializer, ProjectSerializer,
)
from core.report_generator import generate_pdf_report, generate_formal_invoice_pdf
try:
    from ai_agent import get_text_suggestion, analyze_file_content
except ImportError:
    def get_text_suggestion(*args, **kwargs): return "AI features are not available."
    def analyze_file_content(*args, **kwargs): return "AI features are not available."
import base64
import os
import uuid


class EmailReportView(views.APIView):
    """
    Receives chat content and target email.
    Generates a PDF and sends it via email.
    """
    def post(self, request):
        email = request.data.get('email')
        content = request.data.get('content')
        title = request.data.get('title', 'Uniform Agri Insight')

        if not email or not content:
            return Response({"error": "Email and content are required."}, status=status.HTTP_400_BAD_REQUEST)

        try:
            # Generate PDF
            pdf_buffer = generate_pdf_report(content, title)
            
            # Create Email
            mail = EmailMessage(
                subject=f"Your Farm Report: {title}",
                body="Please find attached the report generated by your Uniform Agri Farm Assistant.",
                from_email='bot@uniform-agri.com',
                to=[email],
            )
            
            # Attach PDF
            mail.attach('report.pdf', pdf_buffer.getvalue(), 'application/pdf')
            
            # Send
            mail.send()
            
            return Response({"message": "Email sent successfully!"})
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

class BusinessReportView(APIView):
    """
    Generates a PDF Business Report and returns the URL.
    """
    permission_classes = [AllowAny]

    def post(self, request):
        today = timezone.now().date()
        total_clients = Client.objects.count()
        active_clients = Client.objects.filter(subscription_end_date__gte=today).count()
        
        total_revenue = Invoice.objects.filter(status='Paid to Us').aggregate(
            total=Sum('total_amount'))['total'] or 0
            
        open_tickets = Ticket.objects.filter(status='Open').count()
        
        # Build Markdown
        content = f"""
# Uniform Agri Business Report
**Generated on:** {today.strftime('%Y-%m-%d')}

## Executive Summary
This report contains a top-level overview of the Uniform Agri system operations.

### Key Performance Indicators
- **Total Farms (Clients):** {total_clients}
- **Active Farms:** {active_clients}
- **Total Revenue Collected:** {total_revenue} EGP
- **Pending Open Tickets:** {open_tickets}

## Financial Status
| Description | Amount |
|---|---|
| Collected Revenue | {total_revenue} EGP |

## Action Items
- Follow up on the {open_tickets} open support tickets.
- Ensure expiring clients are contacted.

---
*Report generated automatically by UA Manager Analytics Engine.*
"""
        
        try:
            from core.report_generator import generate_pdf_report
            pdf_buffer = generate_pdf_report(content, title="Business Analytics Report")
            
            # Save the file to media so it can be downloaded
            filename = f"business_report_{uuid.uuid4().hex[:8]}.pdf"
            reports_dir = os.path.join(settings.MEDIA_ROOT, 'reports')
            os.makedirs(reports_dir, exist_ok=True)
            
            filepath = os.path.join(reports_dir, filename)
            with open(filepath, 'wb') as f:
                f.write(pdf_buffer.getvalue())
                
            file_url = request.build_absolute_uri(settings.MEDIA_URL + f"reports/{filename}")
            return Response({'pdf_url': file_url})
        except Exception as e:
            return Response({'error': str(e)}, status=500)

class CustomReportView(views.APIView):
    """
    Accepts arbitrary markdown content and a title to generate a styled PDF report.
    Returns the URL to the generated PDF.
    """
    def post(self, request):
        from datetime import datetime as _dt
        _now = _dt.now()
        _default_title = f'Custom Report — {_now.strftime("%B %Y")}'
        title = request.data.get('title', _default_title)
        content = request.data.get('content')
        
        if not content:
            return Response({"error": "Content is required to generate a report."}, status=status.HTTP_400_BAD_REQUEST)

        try:
            pdf_buffer = generate_pdf_report(content, title=title)
            
            # Save the file to media so it can be downloaded
            filename = f"custom_report_{uuid.uuid4().hex[:8]}.pdf"
            reports_dir = os.path.join(settings.MEDIA_ROOT, 'reports')
            os.makedirs(reports_dir, exist_ok=True)
            
            filepath = os.path.join(reports_dir, filename)
            with open(filepath, 'wb') as f:
                f.write(pdf_buffer.getvalue())
                
            file_url = request.build_absolute_uri(settings.MEDIA_URL + f"reports/{filename}")
            return Response({'pdf_url': file_url})
        except Exception as e:
            return Response({'error': str(e)}, status=500)


class ReportBuilderView(views.APIView):
    """
    Data-driven report builder. Accepts selected modules + filters,
    queries real data, formats into markdown tables, and generates PDF.
    
    POST body:
    {
        "title": "My Report",
        "modules": [
            { "key": "clients", "filters": { "status": "active", ... } },
            { "key": "invoices", "filters": { "status": "Due", "date_from": "2025-01-01" } },
            ...
        ]
    }
    """
    permission_classes = [AllowAny]

    def post(self, request):
        from datetime import datetime as _dt
        _now = _dt.now()
        _mods = request.data.get('modules', [])
        _mod_names = [m.get('key', '').replace('_', ' ').title() for m in _mods]
        _default_title = (', '.join(_mod_names) + f' Report — {_now.strftime("%B %Y")}') if _mod_names else f'Business Report — {_now.strftime("%B %Y")}'
        title = request.data.get('title') or _default_title
        modules = request.data.get('modules', [])

        if not modules:
            return Response({'error': 'At least one module must be selected.'}, status=400)

        sections = []
        summary_stats = {}

        for mod in modules:
            key = mod.get('key')
            filters = mod.get('filters', {})

            if key == 'clients':
                qs = Client.objects.all()
                today = timezone.now().date()

                fstatus = filters.get('status')
                if fstatus == 'active':
                    qs = qs.filter(subscription_end_date__gte=today)
                elif fstatus == 'expired':
                    qs = qs.filter(subscription_end_date__lt=today)
                elif fstatus == 'expiring':
                    qs = qs.filter(
                        subscription_end_date__gte=today,
                        subscription_end_date__lte=today + timedelta(days=60)
                    )
                if filters.get('demo_only'):
                    qs = qs.filter(is_demo=True)
                if filters.get('livestock_type'):
                    qs = qs.filter(livestock_type=filters['livestock_type'])

                rows = []
                for c in qs:
                    end = c.subscription_end_date
                    stat = 'Active' if end and end >= today else 'Expired'
                    rows.append([c.name, c.farm_name, c.phone or '-', str(end) if end else '-', stat, getattr(c, 'livestock_type', '-')])

                summary_stats['Total Clients'] = len(rows)
                header = '| Name | Farm | Phone | Subscription End | Status | Livestock |\n|---|---|---|---|---|---|\n'
                body = '\n'.join([f'| {" | ".join(map(str, r))} |' for r in rows]) if rows else '| No data | | | | | |'
                sections.append(f'## Clients\n\n{header}{body}\n')

            elif key == 'invoices':
                qs = Invoice.objects.select_related('client').all()

                if filters.get('status'):
                    qs = qs.filter(status=filters['status'])
                if filters.get('type'):
                    qs = qs.filter(invoice_type=filters['type'])
                if filters.get('date_from'):
                    qs = qs.filter(created_at__date__gte=filters['date_from'])
                if filters.get('date_to'):
                    qs = qs.filter(created_at__date__lte=filters['date_to'])

                rows = []
                total_amount = 0
                for inv in qs:
                    amt = float(inv.total_amount or 0)
                    total_amount += amt
                    rows.append([
                        inv.client.name if inv.client else '-',
                        inv.invoice_type or '-',
                        f'${amt:,.2f}',
                        inv.status or '-',
                        str(inv.created_at.date()) if inv.created_at else '-'
                    ])

                summary_stats['Total Invoices'] = len(rows)
                summary_stats['Total Amount'] = f'${total_amount:,.2f}'
                header = '| Client | Type | Amount | Status | Date |\n|---|---|---|---|---|\n'
                body = '\n'.join([f'| {" | ".join(r)} |' for r in rows]) if rows else '| No data | | | | |'
                sections.append(f'## Invoices\n\n{header}{body}\n')

            elif key == 'tickets':
                qs = Ticket.objects.select_related('client').all()

                if filters.get('status'):
                    qs = qs.filter(status=filters['status'])
                if filters.get('category'):
                    qs = qs.filter(category=filters['category'])
                if filters.get('date_from'):
                    qs = qs.filter(created_at__date__gte=filters['date_from'])
                if filters.get('date_to'):
                    qs = qs.filter(created_at__date__lte=filters['date_to'])

                rows = []
                for t in qs:
                    desc = t.issue_description[:60] + '...' if len(t.issue_description) > 60 else t.issue_description
                    rows.append([
                        t.client.name if t.client else '-',
                        t.category or '-',
                        t.status or '-',
                        desc,
                        str(t.created_at.date()) if t.created_at else '-'
                    ])

                summary_stats['Total Tickets'] = len(rows)
                header = '| Client | Category | Status | Description | Date |\n|---|---|---|---|---|\n'
                body = '\n'.join([f'| {" | ".join(r)} |' for r in rows]) if rows else '| No data | | | | |'
                sections.append(f'## Tickets\n\n{header}{body}\n')

            elif key == 'payments':
                qs = Payment.objects.select_related('invoice', 'invoice__client').all()

                if filters.get('direction'):
                    qs = qs.filter(direction=filters['direction'])
                if filters.get('date_from'):
                    qs = qs.filter(date__gte=filters['date_from'])
                if filters.get('date_to'):
                    qs = qs.filter(date__lte=filters['date_to'])

                rows = []
                total_paid = 0
                for p in qs:
                    amt = float(p.amount or 0)
                    total_paid += amt
                    client_name = p.invoice.client.name if p.invoice and p.invoice.client else '-'
                    rows.append([
                        client_name,
                        f'${amt:,.2f}',
                        p.direction or '-',
                        str(p.date) if p.date else '-'
                    ])

                summary_stats['Total Payments'] = len(rows)
                summary_stats['Total Paid'] = f'${total_paid:,.2f}'
                header = '| Client | Amount | Direction | Date |\n|---|---|---|---|\n'
                body = '\n'.join([f'| {" | ".join(r)} |' for r in rows]) if rows else '| No data | | | |'
                sections.append(f'## Payments\n\n{header}{body}\n')

            elif key == 'serials':
                qs = GeneticsSerial.objects.select_related('client').all()

                if filters.get('product_type'):
                    qs = qs.filter(product_type=filters['product_type'])
                if filters.get('status') == 'active':
                    qs = qs.filter(is_active=True)
                elif filters.get('status') == 'inactive':
                    qs = qs.filter(is_active=False)
                if filters.get('assigned') == 'assigned':
                    qs = qs.filter(client__isnull=False)
                elif filters.get('assigned') == 'unassigned':
                    qs = qs.filter(client__isnull=True)

                rows = []
                for s in qs:
                    rows.append([
                        s.serial_number or '-',
                        s.client.farm_name if s.client else 'Unassigned',
                        s.product_type or '-',
                        'Active' if s.is_active else 'Inactive',
                        str(s.assigned_date) if s.assigned_date else '-'
                    ])

                summary_stats['Total Serials'] = len(rows)
                header = '| Serial # | Client | Product | Status | Assigned Date |\n|---|---|---|---|---|\n'
                body = '\n'.join([f'| {" | ".join(r)} |' for r in rows]) if rows else '| No data | | | | |'
                sections.append(f'## 4Genetics Serials\n\n{header}{body}\n')

            elif key == 'projects':
                qs = Project.objects.all()
                if filters.get('status'):
                    qs = qs.filter(status=filters['status'])

                rows = []
                for p in qs:
                    desc = (p.description[:60] + '...') if p.description and len(p.description) > 60 else (p.description or '-')
                    rows.append([
                        p.name,
                        p.status or '-',
                        desc,
                        str(p.created_at.date()) if p.created_at else '-'
                    ])

                summary_stats['Total Projects'] = len(rows)
                header = '| Name | Status | Description | Created |\n|---|---|---|---|\n'
                body = '\n'.join([f'| {" | ".join(r)} |' for r in rows]) if rows else '| No data | | | |'
                sections.append(f'## Projects\n\n{header}{body}\n')

        # Build summary stats section
        if summary_stats:
            stats_header = '| Metric | Value |\n|---|---|\n'
            stats_body = '\n'.join([f'| {k} | {v} |' for k, v in summary_stats.items()])
            summary_section = f'## Report Summary\n\n{stats_header}{stats_body}\n\n---\n\n'
        else:
            summary_section = ''

        full_content = summary_section + '\n\n'.join(sections)

        try:
            pdf_buffer = generate_pdf_report(full_content, title=title)
            filename = f"report_{uuid.uuid4().hex[:8]}.pdf"
            reports_dir = os.path.join(settings.MEDIA_ROOT, 'reports')
            os.makedirs(reports_dir, exist_ok=True)
            filepath = os.path.join(reports_dir, filename)
            with open(filepath, 'wb') as f:
                f.write(pdf_buffer.getvalue())
            file_url = request.build_absolute_uri(settings.MEDIA_URL + f"reports/{filename}")
            return Response({'pdf_url': file_url, 'preview_content': full_content})
        except Exception as e:
            return Response({'error': str(e)}, status=500)


class ReportBuilderPreviewView(views.APIView):
    """
    Returns just the data preview (no PDF) for the report builder.
    Same request body as ReportBuilderView but returns JSON data tables.
    """
    permission_classes = [AllowAny]

    def post(self, request):
        modules = request.data.get('modules', [])
        result = {}
        today = timezone.now().date()

        for mod in modules:
            key = mod.get('key')
            filters = mod.get('filters', {})

            if key == 'clients':
                qs = Client.objects.all()
                fstatus = filters.get('status')
                if fstatus == 'active':
                    qs = qs.filter(subscription_end_date__gte=today)
                elif fstatus == 'expired':
                    qs = qs.filter(subscription_end_date__lt=today)
                elif fstatus == 'expiring':
                    qs = qs.filter(subscription_end_date__gte=today, subscription_end_date__lte=today + timedelta(days=60))
                if filters.get('demo_only'):
                    qs = qs.filter(is_demo=True)
                result['clients'] = {
                    'columns': ['Name', 'Farm', 'Phone', 'Subscription End', 'Status'],
                    'rows': [
                        [c.name, c.farm_name, c.phone or '-',
                         str(c.subscription_end_date) if c.subscription_end_date else '-',
                         'Active' if c.subscription_end_date and c.subscription_end_date >= today else 'Expired']
                        for c in qs
                    ],
                    'count': qs.count()
                }

            elif key == 'invoices':
                qs = Invoice.objects.select_related('client').all()
                if filters.get('status'):
                    qs = qs.filter(status=filters['status'])
                if filters.get('type'):
                    qs = qs.filter(invoice_type=filters['type'])
                if filters.get('date_from'):
                    qs = qs.filter(created_at__date__gte=filters['date_from'])
                if filters.get('date_to'):
                    qs = qs.filter(created_at__date__lte=filters['date_to'])
                result['invoices'] = {
                    'columns': ['Client', 'Type', 'Amount', 'Status', 'Date'],
                    'rows': [
                        [inv.client.name if inv.client else '-', inv.invoice_type or '-',
                         f'${float(inv.total_amount or 0):,.2f}', inv.status or '-',
                         str(inv.created_at.date()) if inv.created_at else '-']
                        for inv in qs
                    ],
                    'count': qs.count(),
                    'total': float(qs.aggregate(total=Sum('total_amount'))['total'] or 0)
                }

            elif key == 'tickets':
                qs = Ticket.objects.select_related('client').all()
                if filters.get('status'):
                    qs = qs.filter(status=filters['status'])
                if filters.get('category'):
                    qs = qs.filter(category=filters['category'])
                if filters.get('date_from'):
                    qs = qs.filter(created_at__date__gte=filters['date_from'])
                if filters.get('date_to'):
                    qs = qs.filter(created_at__date__lte=filters['date_to'])
                result['tickets'] = {
                    'columns': ['Client', 'Category', 'Status', 'Description', 'Date'],
                    'rows': [
                        [t.client.name if t.client else '-', t.category or '-', t.status or '-',
                         (t.issue_description[:60] + '...') if len(t.issue_description) > 60 else t.issue_description,
                         str(t.created_at.date()) if t.created_at else '-']
                        for t in qs
                    ],
                    'count': qs.count()
                }

            elif key == 'payments':
                qs = Payment.objects.select_related('invoice', 'invoice__client').all()
                if filters.get('direction'):
                    qs = qs.filter(direction=filters['direction'])
                if filters.get('date_from'):
                    qs = qs.filter(date__gte=filters['date_from'])
                if filters.get('date_to'):
                    qs = qs.filter(date__lte=filters['date_to'])
                result['payments'] = {
                    'columns': ['Client', 'Amount', 'Direction', 'Date'],
                    'rows': [
                        [p.invoice.client.name if p.invoice and p.invoice.client else '-',
                         f'${float(p.amount or 0):,.2f}', p.direction or '-',
                         str(p.date) if p.date else '-']
                        for p in qs
                    ],
                    'count': qs.count(),
                    'total': float(qs.aggregate(total=Sum('amount'))['total'] or 0)
                }

            elif key == 'serials':
                qs = GeneticsSerial.objects.select_related('client').all()
                if filters.get('product_type'):
                    qs = qs.filter(product_type=filters['product_type'])
                if filters.get('status') == 'active':
                    qs = qs.filter(is_active=True)
                elif filters.get('status') == 'inactive':
                    qs = qs.filter(is_active=False)
                if filters.get('assigned') == 'assigned':
                    qs = qs.filter(client__isnull=False)
                elif filters.get('assigned') == 'unassigned':
                    qs = qs.filter(client__isnull=True)
                result['serials'] = {
                    'columns': ['Serial #', 'Client', 'Product', 'Status', 'Assigned Date'],
                    'rows': [
                        [s.serial_number or '-', s.client.farm_name if s.client else 'Unassigned',
                         s.product_type or '-', 'Active' if s.is_active else 'Inactive',
                         str(s.assigned_date) if s.assigned_date else '-']
                        for s in qs
                    ],
                    'count': qs.count()
                }

            elif key == 'projects':
                qs = Project.objects.all()
                if filters.get('status'):
                    qs = qs.filter(status=filters['status'])
                result['projects'] = {
                    'columns': ['Name', 'Status', 'Description', 'Created'],
                    'rows': [
                        [p.name, p.status or '-',
                         (p.description[:60] + '...') if p.description and len(p.description) > 60 else (p.description or '-'),
                         str(p.created_at.date()) if p.created_at else '-']
                        for p in qs
                    ],
                    'count': qs.count()
                }

        return Response(result)
