# Generated by Django 5.2.10 on 2026-01-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contacts',
            field=models.TextField(blank=True, help_text='Additional contacts'),
        ),
        migrations.AddField(
            model_name='client',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_modules',
            field=models.TextField(blank=True, help_text='Details of subscription modules'),
        ),
    ]
