# Generated by Django 5.2.10 on 2026-01-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_contacts_client_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='client',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='client',
            name='general_notes',
            field=models.TextField(blank=True, help_text='Additional notes/contacts'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(blank=True, help_text='e.g. Manager, Herdsman, Owner', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.client')),
            ],
        ),
    ]
