# Generated by Django 5.2.10 on 2026-01-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_client_contacts_remove_client_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
