# Generated by Django 5.2.10 on 2026-02-01 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ticket_status_and_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='demo_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='demo_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Is this farm in demo/trial mode?'),
        ),
        migrations.CreateModel(
            name='GeneticsSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('product_type', models.CharField(choices=[('Milk Meter', 'Milk Meter'), ('Activity Collar', 'Activity Collar'), ('Rumination Tag', 'Rumination Tag'), ('Heat Detection', 'Heat Detection'), ('Other', 'Other')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genetics_serials', to='core.client')),
            ],
            options={
                'verbose_name': '4Genetics Serial',
                'verbose_name_plural': '4Genetics Serials',
                'ordering': ['-created_at'],
            },
        ),
    ]
