# Generated by Django 5.2.10 on 2026-02-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='farm_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Paid to Us', 'Paid to Us'), ('Paid to Uniform', 'Paid to Uniform'), ('Due', 'Due')], db_index=True, default='Due', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Database', 'Database'), ('Milk Meter', 'Milk Meter'), ('Activity System', 'Activity System'), ('Other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=20),
        ),
    ]
