# Generated by Django 5.2.10 on 2026-02-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_client_farm_name_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
