# Generated by Django 5.2.10 on 2026-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='selected_modules',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='core.subscriptionmodule'),
        ),
        migrations.AddField(
            model_name='subscriptionmodule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Module price in EGP', max_digits=10),
        ),
    ]
