# Generated by Django 5.2.10 on 2026-02-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_invoice_selected_modules_subscriptionmodule_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost price (what we pay Uniform Agri)', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total customer price (what the farm pays us)', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Invoice notes'),
        ),
        migrations.AlterField(
            model_name='subscriptionmodule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price in EGP (what we pay Uniform Agri)', max_digits=10),
        ),
    ]
