# Generated by Django 5.2.10 on 2026-02-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_invoice_cost_total_invoice_customer_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('Renewal Invoice', 'Renewal Invoice'), ('Purchase Invoice', 'Purchase Invoice'), ('Purchase Quotation', 'Purchase Quotation')], max_length=30),
        ),
    ]
