# Generated by Django 5.2.10 on 2026-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_clientfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('whatsapp', 'WhatsApp Screenshot')], db_index=True, default='general', max_length=20),
        ),
    ]
