# Generated by Django 5.2.10 on 2026-03-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_clientfile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Related contact person', max_length=255),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the file or screenshot', max_length=500),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='file_date',
            field=models.DateField(blank=True, help_text='Date of the file or screenshot', null=True),
        ),
    ]
