# Generated by Django 5.2.10 on 2026-03-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_clientfile_contact_person_clientfile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Issue Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person related to this ticket', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
