# Generated by Django 5.2.10 on 2026-03-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_seed_issue_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_4genetics_college',
            field=models.BooleanField(default=False, help_text='Is this a 4Genetics College?'),
        ),
    ]
