# Generated by Django 5.2.10 on 2026-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_client_is_4genetics_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticsserial',
            name='modules',
            field=models.TextField(blank=True, help_text='Subscription modules for this college'),
        ),
        migrations.AddField(
            model_name='geneticsserial',
            name='role',
            field=models.CharField(blank=True, help_text='Role or position at the college', max_length=255),
        ),
        migrations.AlterField(
            model_name='geneticsserial',
            name='product_type',
            field=models.CharField(choices=[('Dairy Cows', 'Dairy Cows'), ('Dairy Buffalos', 'Dairy Buffalos'), ('Fattening', 'Fattening'), ('Sheep and Goat', 'Sheep and Goat')], max_length=100),
        ),
    ]
