# Generated by Django 5.2.10 on 2026-03-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_update_genetics_serial_product_types_add_role_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionmodule',
            name='price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_dairylive',
            field=models.BooleanField(default=False, help_text='DairyLive customer? Gives 50% discount on purchase customer price'),
        ),
        migrations.AddField(
            model_name='subscriptionmodule',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost for NEW PURCHASE (what we pay Uniform Agri)', max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionmodule',
            name='renewal_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost for RENEWAL (what we pay Uniform Agri)', max_digits=10),
        ),
    ]
