# Generated by Django 5.2.10 on 2026-03-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_subscriptionmodule_dual_pricing_invoice_dairylive'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('EGP', 'Egyptian Pound (EGP)')], default='EUR', help_text='Currency for this invoice (EUR = base price, EGP = converted at exchange rate)', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='EUR→EGP exchange rate used at time of invoice creation', max_digits=10, null=True),
        ),
    ]
