# Generated by Django 5.2.10 on 2026-03-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_invoice_currency_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_to_uniform',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Cancelled', 'Cancelled'), ('Unknown', 'Unknown')], default='No', help_text='Have we paid Uniform Agri for this invoice?', max_length=20),
        ),
    ]
