# Generated by Django 5.2.10 on 2026-03-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_invoice_paid_to_uniform'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='livestock_type',
            field=models.CharField(choices=[('Dairy Cows', 'Dairy Cows'), ('Dairy Buffalos', 'Dairy Buffalos'), ('Fattening', 'Fattening'), ('Sheep and Goat', 'Sheep and Goat')], default='Dairy Cows', max_length=100),
        ),
    ]
