# Generated by Django 5.2.10 on 2026-03-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_client_livestock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticsserial',
            name='college_name',
            field=models.CharField(blank=True, help_text='Direct college name instead of Client relation', max_length=255),
        ),
    ]
