# Generated by Django 5.2.10 on 2026-03-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_geneticsserial_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticsserial',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geneticsserial',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
