# Generated by Django 5.2.10 on 2026-03-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_geneticsserial_end_date_geneticsserial_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodule',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base List Price for NEW PURCHASE', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionmodule',
            name='renewal_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base List Price for RENEWAL', max_digits=10),
        ),
    ]
