# Generated by Django 5.2.10 on 2026-03-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_subscriptionmodule_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_quoted',
            field=models.BooleanField(default=False, help_text='Is this a farm that only has quotations?'),
        ),
    ]
