# Generated by Django 5.2.10 on 2026-03-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_client_is_quoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
