# Generated by Django 5.2.10 on 2026-03-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_client_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='include_vat',
            field=models.BooleanField(default=False, help_text='Include 14% Value Added Tax on the total amount'),
        ),
    ]
